name: Elite Human Performance
favicon: null
layout_spectrum: 0.508784489473328
typography_spectrum: 0.975839038612321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.48487651301547885
  lightness: 0.17882168176583946
  saturation: 0.671932052122429
  rhythmicContrast: 0.05819777701981366
purpose: []
